// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFT2JEujgl49fqjoQRpHixF5_sIO3eeE',
    appId: '1:364126206276:android:b79a1e5d10fa0702bcff11',
    messagingSenderId: '364126206276',
    projectId: 'home-automation-460908',
    databaseURL: 'https://home-automation-460908-default-rtdb.firebaseio.com',
    storageBucket: 'home-automation-460908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4jLXeNPMZ_QnqCqgGUWb5ccBm54vKSQ',
    appId: '1:364126206276:ios:cb0548b402c83db5bcff11',
    messagingSenderId: '364126206276',
    projectId: 'home-automation-460908',
    databaseURL: 'https://home-automation-460908-default-rtdb.firebaseio.com',
    storageBucket: 'home-automation-460908.firebasestorage.app',
    androidClientId: '364126206276-9b0spsahvs8b4id4o7v3jrdau90kr88d.apps.googleusercontent.com',
    iosClientId: '364126206276-ocothje56lfopfls1sue903g6oe0arbo.apps.googleusercontent.com',
    iosBundleId: 'com.banamaduwa.v0a1',
  );

}